"""initial

Revision ID: 06fe3009fdde
Revises: 
Create Date: 2026-02-21 11:36:59.439674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06fe3009fdde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent_type', sa.String(length=50), nullable=True),
    sa.Column('intent_data_json', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'CANCELLED', 'SNOOZED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'NONE', name='priority'), nullable=False),
    sa.Column('energy_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='energylevel'), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('context', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_time', sa.String(length=5), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('recurrence_type', sa.Enum('NONE', 'DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'CUSTOM', name='recurrencetype'), nullable=False),
    sa.Column('recurrence_interval', sa.Integer(), nullable=True),
    sa.Column('recurrence_days', sa.String(length=20), nullable=True),
    sa.Column('recurrence_end_date', sa.Date(), nullable=True),
    sa.Column('parent_task_id', sa.String(length=36), nullable=True),
    sa.Column('times_snoozed', sa.Integer(), nullable=False),
    sa.Column('times_rescheduled', sa.Integer(), nullable=False),
    sa.Column('original_due_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_notes')
    op.drop_table('tasks')
    op.drop_table('conversation_log')
    # ### end Alembic commands ###
